### ISSUE TITLE
Doesn't actually work

### ISSUE THREAD

**Issue by Southclaws** [mybb/docker#2]
Ran the example, also ran a slightly more filled-in config for a production deployment, fpm seems to be misconfigured (I'm not a PHP user so I'm only guessing).

Once the container is up, hitting the fpm endpoint just results in `curl: (56) Recv failure: Connection reset by peer`, did this from inside the container to rule out any possible Docker network issues.

Here's a configuration to reproduce, just run this and curl `localhost:9000` or `exec` into the container and do the same:

```yaml
version: "3.5"

networks:
    default:
        external:
            name: gateway
    database:
        driver: bridge
        internal: true

services:
    mybb:
        image: mybb/mybb:latest
        volumes:
            - ${DATA_DIR}/burgershot/mybb:/var/www/html
        networks:
            - default
            - database
        labels:
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:example.com
            - traefik.frontend.headers.SSLRedirect=false
            - traefik.port=9000

    postgresql:
        image: postgres:10.4
        environment:
            POSTGRES_DB: mybb
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: mybb
        networks:
            - database
        volumes:
            - ${DATA_DIR}/mybb/postgres/data:/var/lib/postgresql/data
```
