### ISSUE TITLE
Can't keep language files

### ISSUE THREAD

**Issue by megan-starr9** [mybb/docker#5]
Heyo!

So - I'm trying to keep my project light by letting the docker image handle the mybb install.  however, this doesn't work because the extract overwrites all files within the destination.  This means my language files get overwritten by the clean image files!

Would it be possible to add a flag to skip already present files on this line?
https://github.com/mybb/docker/blob/master/docker-entrypoint.sh#L10
By adding this flag:
https://stackoverflow.com/a/51171675

My docker setup would ideally look like the following:

```yaml
version: '3.7'

services:
  mybb:
    build:
      context: ./site
    ports:
      - 9000:9000
    depends_on:
      - mysql
    volumes:
      - ./site/inc/plugins:/var/www/html/inc/plugins
      - ./site/inc/config.php:/var/www/html/inc/config.php
      - ./site/inc/languages:/var/www/html/inc/languages
      - site:/var/www/html

  nginx:
    build:
      context: ./nginx
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - mybb
    volumes:
      - site:/var/www/html:ro

  mysql:
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql

volumes:
  site:
```

And when mybb installs, it ideally would not overwrite my desired config.php or language file updates!  thanks!
